version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  exclude-dirs-use-default: false
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll

linters:
  enable:
    - dupl
    - errcheck
    - copyloopvar
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

formatters:
  enable:
    - gofmt
    - goimports

config:
  linters-settings:
    revive:
      rules:
        - name: comment-spacings
