---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-observability-vexxhost-dev-v1alpha1-metricsserver
  failurePolicy: Fail
  name: vmetricsserver.kb.io
  rules:
  - apiGroups:
    - observability.vexxhost.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - metricsservers
  sideEffects: None
