# This rule is not used by the project metrics-server-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over observability.vexxhost.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: metrics-server-operator
    app.kubernetes.io/managed-by: kustomize
  name: metrics-server-admin-role
rules:
- apiGroups:
  - observability.vexxhost.dev
  resources:
  - metricsservers
  verbs:
  - '*'
- apiGroups:
  - observability.vexxhost.dev
  resources:
  - metricsservers/status
  verbs:
  - get
