apiVersion: observability.vexxhost.dev/v1alpha1
kind: MetricsServer
metadata:
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/instance: metrics-server-sample
    app.kubernetes.io/part-of: metrics-server-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: metrics-server-operator
  name: metrics-server-sample
spec:
  # Default configuration - equivalent to the Ansible role setup
  image: "registry.k8s.io/metrics-server/metrics-server:v0.7.2"
  replicas: 1
  kubeletInsecureTLS: true
  priorityClassName: "system-cluster-critical"
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  args:
    - --metric-resolution=15s