# This configuration is for teaching kustomize how to update name ref and var substitution
nameReference:
- kind: Issuer
  group: cert-manager.io
  fieldSpecs:
  - kind: Certificate
    group: cert-manager.io
    path: spec/issuerRef/name
- kind: Secret
  fieldSpecs:
  - kind: Deployment
    path: spec/template/spec/volumes/secret/secretName

varReference:
- kind: Certificate
  group: cert-manager.io
  path: spec/commonName
- kind: Certificate
  group: cert-manager.io
  path: spec/dnsNames
- kind: Certificate
  group: cert-manager.io
  path: spec/subject/organizations